package main

// # 2) Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// SumFiboEven sum all the even number in fibonaccy sequence until n
func SumFiboEven(n int) int {
	a, b := 1, 1
	sum := 0

	for b <= n {
		a, b = b, a+b
		if b%2 == 0 {
			sum += b
		}
	}

	return sum
}
